### ISSUE TITLE
灵摆卡生成时，由于数据源卡图尺寸问题导致生成的卡图部分被遮挡

### ISSUE THREAD

**Issue by xiluzi** [kooriookami/tools-vue#10]
今天第一次使用这个网站，感觉很不错。给作者点个👍。

**问题描述：**

但是也同时发现了一个问题。即灵摆卡生成时，由于数据源卡图尺寸问题导致生成的卡图部分被遮挡。

**复现方法：**

当卡密输 _98452268_ 或者 _88919365_ 等搜索时，会出现卡图下半部分被遮挡的情况。

![image](https://user-images.githubusercontent.com/25475411/183241759-b8a8883b-127d-4180-a0c1-d4910a0fb54b.png)

而当卡密输 _40227329_ 搜索时，卡图正常显示。

![image](https://user-images.githubusercontent.com/25475411/183241731-5726cf58-ad0d-4163-9ced-5e520109576b.png)

**原因：**

当我查看 network 请求的 api 的时候，发现请求的是第三方的 https://storage.googleapis.com/ygoprodeck.com/pics_artgame/{卡密}.jpg 接口。

然后发现，第三方的卡图接口，对于灵摆卡图，存在2种不同的尺寸。 

对于 _98452268_ ，https://storage.googleapis.com/ygoprodeck.com/pics_artgame/98452268.jpg 该接口返回的卡图没有下半部分，

而对于 _40227329_，https://storage.googleapis.com/ygoprodeck.com/pics_artgame/40227329.jpg 该接口返回的卡图有下半部分。

因此如果以同样的逻辑来处理的时候，对于 _98452268_ 的显示，就会出现下半部分被遮挡的情况。

**解决方法（仅代表个人建议）：**

因为第三方接口返回的图片我们无法控制，那只能说，接口返回的时候，判断下图片尺寸（视情况先判断卡片类型是否为灵摆卡）。

1. 如果接口返回的尺寸是全身的，则以现在同样的逻辑处理。

2. 如果接口返回的尺寸只有半身，则用新的逻辑处理。

**Comment by kooriookami** [comment]
感谢你的提问，灵摆卡图确实有这样情况。我之前对卡图处理是从卡图上面截取一个正方形，这种情况对于高度大于宽度的情况合适。现在出现了高度小于宽度的情况，可能截取存在问题，应该截取一个居中的内接正方形。我回头看看这个处理方法可不可行哈哈。
