### ISSUE TITLE
更改字体无反应

### ISSUE THREAD

**Issue by tony-bzzhao** [kooriookami/tools-vue#11]
您好。使用点阵字生成器时，将默认的宋体更改成别的字体，没有反应，导出还是宋体。谢谢！

**Comment by kooriookami** [comment]
> 您好。使用点阵字生成器时，将默认的宋体更改成别的字体，没有反应，导出还是宋体。谢谢！

如果是windows系统，一般都默认安装了列表中出现的字体。如果没有反应可以重新安装一下字体，
