### ISSUE TITLE
已经是会员的情况下 扩充容量，必选充值会员，这不合理，我只想扩容，不想充值会员，建议会员充值可以取消选择

### ISSUE THREAD

**Issue by 15211456210** [kooriookami/tools-vue#13]

**Comment by kooriookami** [comment]
@15211456210 我有思考过这个问题，单独扩容会存在一个问题，用户充值月卡15天后选择扩容，继续收费1个月的扩容费用户会不满意。目前做法是只要再次购买会员+扩容，之前已存在的会员时长都可以使用扩容，算是赠送用户的。极端情况下，当一个用户购买年卡不扩容后，再选一个月卡+1100张扩容，他甚至可以捡漏300多元，使用13个月的扩容。
