### ISSUE TITLE
好像数据有点旧了

### ISSUE THREAD

**Issue by HenryFishYu** [kooriookami/tools-vue#4]
https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp
这个就查询不到，但是卡图还是有的
https://storage.googleapis.com/ygoprodeck.com/pics_artgame/645794.jpg
同时ygopro的数据库也是存在这张的,thanks in advance

**Comment by HenryFishYu** [comment]
> 现在应该好了，这个数据库时不时会出些问题-w- 在 2021-04-04 23:02:52，"HenryYu" ***@***.***> 写道： https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp 这个就查询不到，但是卡图还是有的 https://storage.googleapis.com/ygoprodeck.com/pics_artgame/645794.jpg 同时ygopro的数据库也是存在这张的,thanks in advance — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

还是有问题，这次变了个545781

**Comment by kooriookami** [comment]
> > 现在应该好了，这个数据库时不时会出些问题-w- 在 2021-04-04 23:02:52，"HenryYu" _**@**_.***> 写道： https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp 这个就查询不到，但是卡图还是有的 https://storage.googleapis.com/ygoprodeck.com/pics_artgame/645794.jpg 同时ygopro的数据库也是存在这张的,thanks in advance — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 还是有问题，这次变了个545781

这个数据库是yugioh omega的数据库，目前是测试版本，可能不太稳定，我这边只能等待更新。

**Comment by HenryFishYu** [comment]
> > > 现在应该好了，这个数据库时不时会出些问题-w- 在 2021-04-04 23:02:52，"HenryYu" _**@**_.***> 写道： https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp 这个就查询不到，但是卡图还是有的 https://storage.googleapis.com/ygoprodeck.com/pics_artgame/645794.jpg 同时ygopro的数据库也是存在这张的,thanks in advance — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 还是有问题，这次变了个545781
> 
> 这个数据库是yugioh omega的数据库，目前是测试版本，可能不太稳定，我这边只能等待更新。

请问这个数据库是card.cdb这个吗，在YGO Omega\YGO Omega_Data\Files\Databases下面是空的，目前在用ygopro的card.cdb数据库。想写一个解析就像https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp一样，别的都能解析出来但是卡包信息解析不出来，找到的API文档缺失了卡包信息部分，请问这个API里面卡包信息部分是怎么解析的

**Comment by kooriookami** [comment]
> > > > 现在应该好了，这个数据库时不时会出些问题-w- 在 2021-04-04 23:02:52，"HenryYu" _**@**_.***> 写道： https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp 这个就查询不到，但是卡图还是有的 https://storage.googleapis.com/ygoprodeck.com/pics_artgame/645794.jpg 同时ygopro的数据库也是存在这张的,thanks in advance — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 还是有问题，这次变了个545781
> > 
> > 
> > 这个数据库是yugioh omega的数据库，目前是测试版本，可能不太稳定，我这边只能等待更新。
> 
> 请问这个数据库是cards.cdb这个吗，在YGO Omega\YGO Omega_Data\Files\Databases下面是空的，目前在用ygopro的cards.cdb数据库。想写一个解析就像https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp 一样，别的都能解析出来但是卡包信息解析不出来，找到的API文档缺失了卡包信息部分，请问这个API里面卡包信息部分是怎么解析的

数据库下载链接是这个，你对比一下看看：https://chocolatecannoli.com/database/OmegaDB.cdb
数据库解析可以参照这个文件：https://github.com/kooriookami/tools-vue/blob/master/src/plugins/yugioh-plugin.js

**Comment by HenryFishYu** [comment]
> > > > > 现在应该好了，这个数据库时不时会出些问题-w- 在 2021-04-04 23:02:52，"HenryYu" _**@**_.***> 写道： https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp 这个就查询不到，但是卡图还是有的 https://storage.googleapis.com/ygoprodeck.com/pics_artgame/645794.jpg 同时ygopro的数据库也是存在这张的,thanks in advance — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > 
> > > > 
> > > > 还是有问题，这次变了个545781
> > > 
> > > 
> > > 这个数据库是yugioh omega的数据库，目前是测试版本，可能不太稳定，我这边只能等待更新。
> > 
> > 
> > 请问这个数据库是cards.cdb这个吗，在YGO Omega\YGO Omega_Data\Files\Databases下面是空的，目前在用ygopro的cards.cdb数据库。想写一个解析就像https://tools.kooriookami.top/api/yugioh/card/645794?lang=jp 一样，别的都能解析出来但是卡包信息解析不出来，找到的API文档缺失了卡包信息部分，请问这个API里面卡包信息部分是怎么解析的
> 
> 数据库下载链接是这个，你对比一下看看：https://chocolatecannoli.com/database/OmegaDB.cdb
> 数据库解析可以参照这个文件：https://github.com/kooriookami/tools-vue/blob/master/src/plugins/yugioh-plugin.js

谢谢，这个数据库就是想找的包含卡包信息的，这个issue我关闭了
