### ISSUE TITLE
画图板操作的一点建议

### ISSUE THREAD

**Issue by btea** [kooriookami/tools-vue#5]
1、在画图板进行文本、图形等绘制时，是否应该禁用右键操作，或者说禁止默认右键弹窗。  
2、文本输入框是否要做个边界处理。

**Comment by kooriookami** [comment]
@btea 右键没有必要禁止，用户可以要操作复制黏贴的功能。文本输入框也不需要边界处理，因为可能会使用边界截断的文字效果。
