### ISSUE TITLE
游戏王卡api的数据哪里获取的？

### ISSUE THREAD

**Issue by VieYang** [kooriookami/tools-vue#6]
RT

**Comment by kooriookami** [comment]
> RT

@VieYang https://duelistsunite.org/omega/OmegaDB.cdb

**Comment by VieYang** [comment]
谢谢。

**Comment by VieYang** [comment]
base64格式的图片是哪里获取的啊？我只找到了全图的，没有找到只有中间的。

https://storage.googleapis.com/ygoprodeck.com/pics_artgame/16178681.jpg

这个图资源？

**Comment by kooriookami** [comment]
> base64格式的图片是哪里获取的啊？我只找到了全图的，没有找到只有中间的。
> 
> https://storage.googleapis.com/ygoprodeck.com/pics_artgame/16178681.jpg
> 
> 这个图资源？

没错

**Comment by VieYang** [comment]
哦，我表达错误了。我的意思是“这个图的资源在哪里能下载，批量获取的那种”

**Comment by jackchen2025** [comment]
存在中文的数据库吗？

**Comment by VieYang** [comment]
@jackchen2025  上面那个db里有中文

**Comment by kooriookami** [comment]
> 哦，我表达错误了。我的意思是“这个图的资源在哪里能下载，批量获取的那种”

不能批量获取。。除非你会写爬虫自己爬数据

**Comment by VieYang** [comment]
好的，谢谢。
