### ISSUE TITLE
灵摆的效果好像都是英文？

### ISSUE THREAD

**Issue by fantasyjqc** [kooriookami/tools-vue#7]
是我的设置问题还是原本就是这样呢？好像所有灵摆的效果都是英文的。

**Comment by kooriookami** [comment]
那就是数据的问题了，跟ygo omega用的同一个数据源

**Comment by fantasyjqc** [comment]
> 那就是数据的问题了，跟ygo omega用的同一个数据源

另外我看有一些卡密无法搜到，是不是因为要等数据更新，在其他卡查平台可以查到。

**Comment by fantasyjqc** [comment]
> 新卡卡密是没有更新，可以尝试用卡名搜索，另外数据是每天凌晨同步的，一直保持最新的。

这几天测试了很多那个数据，发现同一张灵摆卡的，英文、简体中文都是正确的，但是繁体中文好像解析有些问题，实际上是有灵摆效果和普通效果的，只不过解析出来好像有些问题，大佬如果有空可以研究下，以这个为例：

简中是对的
![image](https://user-images.githubusercontent.com/4988150/156888604-7ee26465-f110-459c-8564-276d7e3c7889.png)

繁中这里，灵摆效果是英文的，灵摆效果和普通效果都放在了效果里，下图1和2。
![image](https://user-images.githubusercontent.com/4988150/156888633-cff45100-3835-415f-be24-6c9e5fef9365.png)

**Comment by fantasyjqc** [comment]
> 新卡卡密是没有更新，可以尝试用卡名搜索，另外数据是每天凌晨同步的，一直保持最新的。

这几天测试了很多那个数据，发现同一张灵摆卡的，英文、简体中文都是正确的，但是繁体中文好像解析有些问题，实际上是有灵摆效果和普通效果的，只不过解析出来好像有些问题，大佬如果有空可以研究下，以这个为例：

简中是对的
![image](https://user-images.githubusercontent.com/4988150/156888604-7ee26465-f110-459c-8564-276d7e3c7889.png)

繁中这里，灵摆效果是英文的，灵摆效果和普通效果都放在了效果里，下图1和2。
![image](https://user-images.githubusercontent.com/4988150/156888633-cff45100-3835-415f-be24-6c9e5fef9365.png)

**Comment by kooriookami** [comment]
@fantasyjqc 确实是这样，数据库中繁中的数据有点错乱，过段时间看看数据源会不会被修复，目前先观望着:D

**Comment by kooriookami** [comment]
这个我暂时修复了，先关了
