### ISSUE TITLE
保存日文卡图时，卡名注音的分割符位置不正确

### ISSUE THREAD

**Issue by Seine-p** [kooriookami/tools-vue#8]
如图，试过了多种分隔符，是我本地的问题吗？
![2](https://user-images.githubusercontent.com/104388543/165155981-8c2b0e7e-212d-44f4-9273-34b3639a4c13.png)
![青眼の白龍](https://user-images.githubusercontent.com/104388543/165155986-4e5fc134-ec4f-45a2-970c-39daf2799213.png)

作为对比，在网页中是这样的

![捕获](https://user-images.githubusercontent.com/104388543/165156201-95261529-a911-48a7-b7d9-cb12fc09efa4.PNG)

**Comment by kooriookami** [comment]
我这边没有问题，你用的啥浏览器呢

**Comment by Seine-p** [comment]
Chrome，版本是100.0.4896.127

**Comment by kooriookami** [comment]
![image](https://user-images.githubusercontent.com/38392315/166179693-f87bc0ba-05d5-4ced-9034-326f6fee329c.png)
我是101版本，没有问题耶，系统是win11

**Comment by Seine-p** [comment]
我的是win10，win10和win11之间有什么更新会涉及到这个吗（笑哭）

**Comment by kooriookami** [comment]
> 我的是win10，win10和win11之间有什么更新会涉及到这个吗（笑哭）

应该关系不大，不知道为什么很神奇。

**Comment by Seine-p** [comment]
猜测是否是字体的原因？
日文卡名具体用的是什么字体呢？

**Comment by kooriookami** [comment]
> 猜测是否是字体的原因？
> 日文卡名具体用的是什么字体呢？
> 
> 另外，我查看了之前的图片，2021年4月时已经有这个问题了

字体是我自己做的，主要用了网上搜集来的游戏王字体，什么df隶书体啥的

**Comment by Seine-p** [comment]
![image](https://user-images.githubusercontent.com/104388543/169530148-2b57e98f-2757-4aed-985c-540d538fcaaf.png)
今天新发现的问题

**Comment by kooriookami** [comment]
是html2canvas那个库的问题，我回滚了，但是分隔符有问题。。

**Comment by kooriookami** [comment]
> ![image](https://user-images.githubusercontent.com/104388543/169530148-2b57e98f-2757-4aed-985c-540d538fcaaf.png)保存到本地后 ![image](https://user-images.githubusercontent.com/104388543/169530567-53b0d9d8-f58e-457c-92e1-63fbc76d2419.png)网页端 今天新发现的问题，推测与更新有关，连同之前的分隔符问题，猜测是eslint导致的

现在应该没问题了，我换了种实现方式，用letter-spacing来实现两端对齐了

**Comment by Seine-p** [comment]
现在分隔符和对齐两个问题都已经解决了，感谢
